# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/trainee',
                'doc_host': 'https://carolbalbs.github.io',
                'git_url': 'https://github.com/carolbalbs/trainee',
                'lib_path': 'trainee'},
  'syms': {'trainee.core': {'trainee.core.foo': ('core.html#foo', 'trainee/core.py')}}}
