project:
  type: website
  preview:
    port: 8080
    browser: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    keep-md: true
    

website:
  title: " "
  favicon: ./images/prancheta2_3.svg
  margin-footer: |
    ![](/images/nomeREAL.png)
  site-url: "https://robochicas.github.io/trainee"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  repo-actions: [issue]
  navbar:
    logo: "/images/nomeREAL.png"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/robochicas
  sidebar:
    style: floating


metadata-files: [sidebar.yml]
