on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important to fetch all branches

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Initialize gh-pages branch (if needed)
        if: "!contains(github.ref, 'gh-pages')"
        run: |
          git fetch origin gh-pages || echo "gh-pages branch does not exist yet"
          quarto publish gh-pages --no-prompt --no-browser

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}